"""Catalogue des connecteurs (aligné panneau n8n Human in the loop)."""

from __future__ import annotations

from typing import Any, Dict, List

SEND_AND_WAIT = "Send and wait for response"

CONNECTOR_SPECS: List[Dict[str, Any]] = [
    {
        "id": "discord",
        "node_type": "connector_discord",
        "label": "Discord",
        "subgroup": SEND_AND_WAIT,
        "send_wait_template": "discord",
        "description": "Send a message and wait for approval in Discord.",
    },
    {
        "id": "gmail",
        "node_type": "connector_gmail",
        "label": "Gmail",
        "subgroup": SEND_AND_WAIT,
        "send_wait_template": "email",
        "description": "Send email and wait for a reply via Gmail.",
    },
    {
        "id": "google_chat",
        "node_type": "connector_google_chat",
        "label": "Google Chat",
        "subgroup": SEND_AND_WAIT,
        "send_wait_template": "google_chat",
        "description": "Send and wait in Google Chat spaces.",
    },
    {
        "id": "microsoft_outlook",
        "node_type": "connector_microsoft_outlook",
        "label": "Microsoft Outlook",
        "subgroup": SEND_AND_WAIT,
        "send_wait_template": "outlook",
        "description": "Outlook message with human response.",
    },
    {
        "id": "microsoft_teams",
        "node_type": "connector_microsoft_teams",
        "label": "Microsoft Teams",
        "subgroup": SEND_AND_WAIT,
        "send_wait_template": "teams",
        "description": "Teams channel message and wait for reply.",
    },
    {
        "id": "send_email",
        "node_type": "connector_send_email",
        "label": "Send Email",
        "subgroup": SEND_AND_WAIT,
        "send_wait_template": "email",
        "credential_type": "smtp",
        "description": "Generic SMTP send and wait for response.",
    },
    {
        "id": "slack",
        "node_type": "connector_slack",
        "label": "Slack",
        "subgroup": SEND_AND_WAIT,
        "send_wait_template": "slack",
        "description": "Slack message and wait for user action.",
    },
    {
        "id": "telegram",
        "node_type": "connector_telegram",
        "label": "Telegram",
        "subgroup": SEND_AND_WAIT,
        "send_wait_template": "telegram",
        "description": "Telegram bot send and wait.",
    },
    {
        "id": "whatsapp",
        "node_type": "connector_whatsapp",
        "label": "WhatsApp Business Cloud",
        "subgroup": SEND_AND_WAIT,
        "send_wait_template": "whatsapp",
        "description": "WhatsApp Business API send and wait.",
    },
    {
        "id": "aws_s3",
        "node_type": "connector_aws_s3",
        "label": "Amazon S3",
        "subgroup": "Cloud & stockage",
        "description": "Lire ou écrire des objets S3.",
    },
    {
        "id": "azure_blob",
        "node_type": "connector_azure_blob",
        "label": "Azure Blob",
        "subgroup": "Cloud & stockage",
        "description": "Stockage blob Microsoft Azure.",
    },
    {
        "id": "google_drive",
        "node_type": "connector_google_drive",
        "label": "Google Drive",
        "subgroup": "Cloud & stockage",
        "description": "Fichiers Google Drive.",
    },
    {
        "id": "sharepoint",
        "node_type": "connector_sharepoint",
        "label": "SharePoint",
        "subgroup": "Cloud & stockage",
        "description": "Bibliothèques SharePoint Online.",
    },
    {
        "id": "postgresql",
        "node_type": "connector_postgresql",
        "label": "PostgreSQL",
        "subgroup": "Bases de données",
        "description": "Connexion PostgreSQL / PostGIS.",
    },
    {
        "id": "mysql",
        "node_type": "connector_mysql",
        "label": "MySQL",
        "subgroup": "Bases de données",
        "description": "Connexion MySQL / MariaDB.",
    },
    {
        "id": "sql_server",
        "node_type": "connector_sql_server",
        "label": "SQL Server",
        "subgroup": "Bases de données",
        "description": "Microsoft SQL Server.",
    },
    {
        "id": "mongodb",
        "node_type": "connector_mongodb",
        "label": "MongoDB",
        "subgroup": "Bases de données",
        "description": "Collections MongoDB.",
    },
    {
        "id": "http_request",
        "node_type": "connector_http",
        "label": "HTTP Request",
        "subgroup": "APIs & web",
        "description": "Appels REST génériques (GET/POST).",
    },
    {
        "id": "webhook",
        "node_type": "connector_webhook",
        "label": "Webhook",
        "subgroup": "APIs & web",
        "description": "Déclencher ou recevoir des webhooks.",
    },
    {
        "id": "graphql",
        "node_type": "connector_graphql",
        "label": "GraphQL",
        "subgroup": "APIs & web",
        "description": "Requêtes GraphQL.",
    },
    {
        "id": "oauth2",
        "node_type": "connector_oauth2",
        "label": "OAuth2",
        "subgroup": "APIs & web",
        "description": "Authentification OAuth2.",
    },
    {
        "id": "wfs",
        "node_type": "connector_wfs",
        "label": "WFS / OGC",
        "subgroup": "SIG & géospatial",
        "description": "Services WFS et flux OGC.",
    },
    {
        "id": "arcgis_rest",
        "node_type": "connector_arcgis_rest",
        "label": "ArcGIS REST",
        "subgroup": "SIG & géospatial",
        "description": "Feature services ArcGIS REST.",
    },
    {
        "id": "mapbox",
        "node_type": "connector_mapbox",
        "label": "Mapbox",
        "subgroup": "SIG & géospatial",
        "description": "Tuiles et API Mapbox.",
    },
    {
        "id": "ftp",
        "node_type": "connector_ftp",
        "label": "FTP",
        "subgroup": "Fichiers & transfert",
        "description": "Transfert FTP.",
    },
    {
        "id": "sftp",
        "node_type": "connector_sftp",
        "label": "SFTP",
        "subgroup": "Fichiers & transfert",
        "description": "Transfert SFTP sécurisé.",
    },
    {
        "id": "smb",
        "node_type": "connector_smb",
        "label": "Partage SMB",
        "subgroup": "Fichiers & transfert",
        "description": "Dossiers réseau Windows / SMB.",
    },
]

HITL_SUBGROUP_ORDER = [
    "Approvals",
    SEND_AND_WAIT,
    "Cloud & stockage",
    "Bases de données",
    "APIs & web",
    "SIG & géospatial",
    "Fichiers & transfert",
]
